apiVersion: v1
kind: Pod
metadata:
  name: flyway
  labels:
    app: flyway
spec:
  restartPolicy: Always
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
    - name: flyway
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      command: ["/flyway/flyway"]
      args: ["migrate"]
      env:
        - name: FLYWAY_SCHEMAS
          valueFrom:
            configMapKeyRef:
              name: flyway-configmap
              key: FLYWAY_SCHEMAS
        - name: FLYWAY_URL
          valueFrom:
            configMapKeyRef:
              name: flyway-configmap
              key: FLYWAY_URL
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: user
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
