apiVersion: v1
kind: Pod
metadata:
  name: flyway
  labels:
    app: flyway
spec:
  restartPolicy: Never
  containers:
    - name: flyway
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      command: ["/flyway/flyway"]
      args: ["migrate"]
      resources:
        {{- toYaml .Values.resources | nindent 12 }}
      env:
        - name: FLYWAY_SCHEMAS
          valueFrom:
            configMapKeyRef:
              name: flyway-configmap
              key: FLYWAY_SCHEMAS
        - name: FLYWAY_URL
          valueFrom:
            configMapKeyRef:
              name: flyway-configmap
              key: FLYWAY_URL
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: user
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
