# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  services:
    auth: "http://auth"
    position: "http://position"
    push: "http://push"
    billing: "http://billing"
    modelEngine: "http://model-engine"
    modelsManager: "http://models-manager"
    redis: "redis:6379"

image:
  nginx:
    repository: nginx
    tag: 1.17.10-alpine
    pullPolicy: IfNotPresent
  gateway:
    repository: sr2020/eva-gateway
    tag: 244e2a4
    pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

global:
  postgres:
    host: postgres

# services
admin-client:
  image:
    repository: sr2020/admin-client
    tag: "b987759"
    pullPolicy: IfNotPresent

auth:
  image:
    repository: sr2020/eva-auth
    tag: "2555e61"
    pullPolicy: IfNotPresent

backup:
  image:
    backup:
      repository: sr2020/krohobor
      tag: latest
      pullPolicy: IfNotPresent
    cron:
      repository: xordiv/docker-alpine-cron
      tag: latest
      pullPolicy: IfNotPresent

billing:
  image:
    repository: sr2020/billingapi
    tag: "d263a32"
    pullPolicy: IfNotPresent

convey:
  image:
    repository: sr2020/eva-gateway-test
    tag: latest
    pullPolicy: IfNotPresent

flyway:
  image:
    repository: sr2020/db
    tag: "0eb548a"
    pullPolicy: IfNotPresent

rc-flyway:
  image:
    repository: sr2020/db
    tag: "0eb548a"
    pullPolicy: IfNotPresent

grafana:
  image:
    repository: grafana/grafana
    tag: latest
    pullPolicy: IfNotPresent

ppa:
  image:
    repository: dockage/phppgadmin
    tag: latest
    pullPolicy: IfNotPresent

position:
  image:
    repository: sr2020/eva-position
    tag: 0bc5990
    pullPolicy: IfNotPresent

postgres:
  image:
    repository: postgres
    tag: 11.7
    pullPolicy: IfNotPresent

redis:
  image:
    repository: redis
    tag: 5.0.8
    pullPolicy: IfNotPresent

push:
  image:
    repository: sr2020/push
    tag: 491a5747f7cf66518f8aee596a18dac49e067e3f
    pullPolicy: IfNotPresent

model-engine:
  image:
    repository: sr2020/model-engine
    tag: 491a5747f7cf66518f8aee596a18dac49e067e3f
    pullPolicy: IfNotPresent

models-manager:
  image:
    repository: sr2020/models-manager
    tag: 491a5747f7cf66518f8aee596a18dac49e067e3f
    pullPolicy: IfNotPresent

rc-web:
  image:
    backend:
      repository: sr2020/testjpa-backend
      tag: "204eef4c"
      pullPolicy: IfNotPresent
    frontend:
      repository: sr2020/testjpa-frontend
      tag: "204eef4c"
      pullPolicy: IfNotPresent

web:
  image:
    backend:
      repository: sr2020/testjpa-backend
      tag: "7afda777"
      pullPolicy: IfNotPresent
    frontend:
      repository: sr2020/testjpa-frontend
      tag: "7afda777"
      pullPolicy: IfNotPresent

# resources
resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
