# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  services:
    auth: "http://auth"
    position: "http://position"
    push: "http://push"
    billing: "http://billing"
    modelEngine: "http://model-engine"
    modelsManager: "http://models-manager"
    redis: "redis:6379"

image:
  repository: sr2020/eva-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

global:
  postgres:
    host: postgres

# services
auth:
  image:
    repository: sr2020/eva-auth
    tag: latest
    pullPolicy: IfNotPresent

admin-client:
  image:
    repository: sr2020/admin-client
    tag: latest
    pullPolicy: IfNotPresent

backup:
  image:
    backup:
      repository: sr2020/krohobor
      tag: latest
      pullPolicy: IfNotPresent
    cron:
      repository: xordiv/docker-alpine-cron
      tag: latest
      pullPolicy: IfNotPresent

billing:
  image:
    repository: sr2020/billingapi
    tag: cc30222
    pullPolicy: IfNotPresent

flyway:
  image:
    repository: sr2020/db
    tag: e9364cd
    pullPolicy: IfNotPresent

rc-flyway:
  image:
    repository: sr2020/db
    tag: latest
    pullPolicy: IfNotPresent

grafana:
  image:
    repository: grafana/grafana
    tag: latest
    pullPolicy: IfNotPresent

ppa:
  image:
    repository: dockage/phppgadmin
    tag: latest
    pullPolicy: IfNotPresent

position:
  image:
    repository: sr2020/eva-position
    tag: latest
    pullPolicy: IfNotPresent

postgres:
  image:
    repository: postgres
    tag: 11.7
    pullPolicy: IfNotPresent

redis:
  image:
    repository: redis
    tag: 5.0.8
    pullPolicy: IfNotPresent

push:
  image:
    repository: sr2020/push
    tag: 262b6c9ee63b0dd1a8a64a1f0a6980f70b2ace6e
    pullPolicy: IfNotPresent

model-engine:
  image:
    repository: sr2020/model-engine
    tag: 262b6c9ee63b0dd1a8a64a1f0a6980f70b2ace6e
    pullPolicy: IfNotPresent

models-manager:
  image:
    repository: sr2020/models-manager
    tag: 262b6c9ee63b0dd1a8a64a1f0a6980f70b2ace6e
    pullPolicy: IfNotPresent

rc-web:
  image:
    backend:
      repository: sr2020/testjpa-backend
      tag: latest
      pullPolicy: IfNotPresent
    frontend:
      repository: sr2020/testjpa-frontend
      tag: k8s
      pullPolicy: IfNotPresent

web:
  image:
    backend:
      repository: sr2020/testjpa-backend
      tag: latest
      pullPolicy: IfNotPresent
    frontend:
      repository: sr2020/testjpa-frontend
      tag: k8s
      pullPolicy: IfNotPresent

# resources
resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
