apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-engine
spec:
  selector:
    matchLabels:
      run: model-engine
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: model-engine
    spec:
      containers:
        - name: model-engine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
