apiVersion: v1
kind: Service
metadata:
  name: model-engine
  labels:
    run: model-engine
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    run: model-engine
