version: "3.6"

services:
  auth-app:
    image: ${AUTH_IMAGE_APP}
    ports:
      - ${AUTH_APP_PORT}:80
    environment:
      SKIP_COMPOSER: 1
      SKIP_CHOWN: 1
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: auth
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_SECRET: ${MAILGUN_SECRET}
    links:
      - postgres

  auth-redis:
    image: ${IMAGE_REDIS}

  position-app:
    image: ${POSITION_IMAGE_APP}
    ports:
      - ${POSITION_APP_PORT}:80
    environment:
      SKIP_COMPOSER: 1
      SKIP_CHOWN: 1
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: position
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    links:
      - postgres

  position-redis:
    image: ${IMAGE_REDIS}

  billingapi-app:
    image: ${BILLINGAPI_IMAGE_APP}
    ports:
      - ${BILLINGAPI_APP_PORT}:80
    environment:
      POSTGRESQLHANGFIRE_USER: ${POSTGRESQLHANGFIRE_USER}
      POSTGRESQLHANGFIRE_PASSWORD: ${POSTGRESQLHANGFIRE_PASSWORD}
      POSTGRESQLBILLING_USER: ${WEB_BACKEND_DBUSER}
      POSTGRESQLBILLING_PASSWORD: ${WEB_BACKEND_DBPASSWORD}
    links:
      - postgres

  gateway-app:
    image: ${GATEWAY_IMAGE_APP}
    ports:
      - ${GATEWAY_APP_PORT}:80
    environment:
      GATEWAY_PORT: 80
      AUTH_HOST: http://auth-app
      POSITION_HOST: http://position-app
      PUSH_HOST: http://push.k8.evarun.ru
      BILLING_HOST: http://billingapi-app
      MODEL_ENGINE_HOST: http://model-engine.k8.evarun.ru
      MODELS_MANAGER_HOST: http://models-manager.k8.evarun.ru
    restart: on-failure
    links:
      - auth-app
      - position-app

  postgres:
    image: ${IMAGE_POSTGRES}
    restart: always
    volumes:
      - eva-platform-postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}

  ppa:
    image: ${IMAGE_PPA}
    restart: always
    ports:
      - 7051:80
    environment:
      PHP_PG_ADMIN_SERVER_HOST: postgres
    links:
      - postgres

  backup:
    image: ${IMAGE_BACKUP}
    environment:
      APP_PORT: 80
      APP_PASSWORD: ${APP_PASSWORD}
      APP_CATALOG: ${APP_CATALOG}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: ${BACKUP_POSTGRES_USER}
      PGPASSWORD: ${BACKUP_POSTGRES_PASSWORD}
    restart: on-failure
    links:
      - postgres

  cron:
    image: ${IMAGE_CRON}
    restart: always
    environment:
      CRON_STRINGS: "0 0 * * * wget --post-data '' http://backup/v1/backup"
    links:
      - backup

  tomcat:
    image: ${IMAGE_TOMCAT}
    ports:
      - ${TOMCAT_PORT}:8080
    restart: always

  flyway:
    image: ${IMAGE_FLYWAY}
    environment:
      FLYWAY_SCHEMAS: public
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    links:
      - postgres

  web-backend:
    image: ${WEB_BACKEND_IMAGE_APP}
    ports:
      - ${WEB_BACKEND_APP_PORT}:8080
    environment:
      JWT_SECRET: ${WEB_BACKEND_SECRET}
      JDBC_URL: jdbc:p6spy:postgresql://postgres:5432/${WEB_BACKEND_DBNAME}
      POSTGRES_USER: ${WEB_BACKEND_DBUSER}
      POSTGRES_PASSWORD: ${WEB_BACKEND_DBPASSWORD}
    links:
      - postgres

  frontend:
    image: ${WEB_FRONTEND_IMAGE_APP}
    ports:
      - ${WEB_FRONTEND_APP_PORT}:80

  admin-client-app:
    image: ${ADMIN_CLIENT_IMAGE_APP}
    ports:
      - ${ADMIN_CLIENT_APP_PORT}:3001
    environment:
      DROPBOX_TOKEN: ${ADMIN_CLIENT_DROPBOX_TOKEN}
      SKIP_PREFLIGHT_CHECK: 1

  grafana:
    image: ${IMAGE_GRAFANA}
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - eva-platform-grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

  rc-web-backend:
    image: ${RC_WEB_BACKEND_IMAGE_APP}
    ports:
      - ${RC_WEB_BACKEND_APP_PORT}:8080
    environment:
      JWT_SECRET: ${RC_WEB_BACKEND_SECRET}
      JDBC_URL: jdbc:p6spy:postgresql://postgres:5432/${RC_WEB_BACKEND_DBNAME}
      POSTGRES_USER: ${RC_WEB_BACKEND_DBUSER}
      POSTGRES_PASSWORD: ${RC_WEB_BACKEND_DBPASSWORD}
    links:
      - postgres

  rc-frontend:
    image: ${RC_WEB_FRONTEND_IMAGE_APP}
    ports:
      - ${RC_WEB_FRONTEND_APP_PORT}:80

volumes:
  eva-platform-postgres:
  eva-platform-grafana:
