version: "3.6"

services:
  postgres:
    volumes:
      - eva-platform-postgres:/var/lib/postgresql/data
      - ./tests/database/postgres:/docker-entrypoint-initdb.d

  cron:
    environment:
      CRON_STRINGS: ""
