version: "3.6"

services:
  gateway-app:
    image: ${GATEWAY_IMAGE_APP}
    ports:
      - ${GATEWAY_APP_PORT}:80
    environment:
      GATEWAY_PORT: 80
      AUTH_HOST: http://auth-app
      POSITION_HOST: http://position-app
      BILLING_HOST: http://billing-app:3000
      PUSH_HOST: http://push-app:3000
    restart: on-failure
    links:
      - auth-app
      - position-app
      - billing-app

  auth-app:
    image: ${AUTH_IMAGE_APP}
    ports:
      - ${AUTH_APP_PORT}:80
    environment:
      SKIP_COMPOSER: 1
      SKIP_CHOWN: 1
    links:
      - database

  auth-redis:
    image: ${IMAGE_REDIS}

  position-app:
    image: ${POSITION_IMAGE_APP}
    ports:
      - ${POSITION_APP_PORT}:80
    environment:
      SKIP_COMPOSER: 1
      SKIP_CHOWN: 1
    links:
      - database

  position-redis:
    image: ${IMAGE_REDIS}

  billing-app:
    image: ${BILLING_IMAGE_APP}
    ports:
      - ${BILLING_APP_PORT}:3000
    environment:
      MYSQL_HOST: database
      MYSQL_DATABASE: billing
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    links:
      - database

  push-app:
    image: ${PUSH_IMAGE_APP}
    ports:
      - ${PUSH_APP_PORT}:3000
    environment:
      MYSQL_HOST: database
      MYSQL_DATABASE: push
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      FIREBASE_SERVER_TOKEN: ${PUSH_FIREBASE_SERVER_TOKEN}
    links:
      - database

  database:
    image: ${IMAGE_DATABASE}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - eva-platform-database:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  eva-platform-database:
