apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    run: grafana
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    run: grafana
