apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-nginx
data:
  nginx.conf: |
    log_format  full  '$remote_addr - $remote_user [$time_local] "$request" '
      '$status $body_bytes_sent "$http_referer" '
      '"$http_user_agent" "$http_x_forwarded_for" $request_time';

    server {
      listen 80;

      access_log  /var/log/nginx/access.log  full;

      location / {
        proxy_pass http://localhost:8080;

        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;
      }
    }
