apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  tls:
    - hosts:
        - gateway.evarun.ru
        - web.evarun.ru
        - rc-web.evarun.ru
        - ppa.evarun.ru
        - push.evarun.ru
        - model-engine.evarun.ru
        - models-manager.evarun.ru
        - admin-client.evarun.ru
      secretName: tls-secret
  rules:
  - host: gateway.evarun.ru
    http:
      paths:
        - backend:
            serviceName: gateway
            servicePort: http
  - host: web.evarun.ru
    http:
      paths:
        - backend:
            serviceName: web
            servicePort: http
  - host: rc-web.evarun.ru
    http:
      paths:
        - backend:
            serviceName: rc-web
            servicePort: http
  - host: ppa.evarun.ru
    http:
      paths:
        - backend:
            serviceName: ppa
            servicePort: http
  - host: push.evarun.ru
    http:
      paths:
        - backend:
            serviceName: push
            servicePort: http
  - host: model-engine.evarun.ru
    http:
      paths:
        - backend:
            serviceName: model-engine
            servicePort: http
  - host: models-manager.evarun.ru
    http:
      paths:
        - backend:
            serviceName: models-manager
            servicePort: http
  - host: admin-client.evarun.ru
    http:
      paths:
        - backend:
            serviceName: admin-client
            servicePort: http
