apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  tls:
    - secretName: tls-secret-production
  rules:
  - host: gateway.production.evarun.ru
    http:
      paths:
        - backend:
            serviceName: gateway
            servicePort: http
  - host: web.production.evarun.ru
    http:
      paths:
        - backend:
            serviceName: web
            servicePort: http
  - host: rc-web.production.evarun.ru
    http:
      paths:
        - backend:
            serviceName: rc-web
            servicePort: http
  - host: ppa.production.evarun.ru
    http:
      paths:
        - backend:
            serviceName: ppa
            servicePort: http
  - host: push.production.evarun.ru
    http:
      paths:
        - backend:
            serviceName: push
            servicePort: http
  - host: model-engine.production.evarun.ru
    http:
      paths:
        - backend:
            serviceName: model-engine
            servicePort: http
  - host: models-manager.production.evarun.ru
    http:
      paths:
        - backend:
            serviceName: models-manager
            servicePort: http
  - host: admin-client.production.evarun.ru
    http:
      paths:
        - backend:
            serviceName: admin-client
            servicePort: http
