# Default values for auth2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  backend:
    repository: sr2020/testjpa-backend
    tag: latest
    pullPolicy: IfNotPresent
  frontend:
    repository: sr2020/testjpa-frontend
    tag: k8s
    pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources:
  frontend:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
  backend:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
