apiVersion: apps/v1
kind: Deployment
metadata:
  name: models-manager
spec:
  selector:
    matchLabels:
      run: models-manager
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: models-manager
    spec:
      containers:
        - name: models-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          env:
            - name: POSTGRESQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: models-manager-configmap
                  key: POSTGRESQL_HOST
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: models-manager-configmap
                  key: POSTGRESQL_DATABASE
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
