apiVersion: v1
kind: Service
metadata:
  name: pg-admin
  labels:
    run: pg-admin
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    run: pg-admin
