apiVersion: v1
kind: Service
metadata:
  name: admin-client
  labels:
    run: admin-client
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3001
  selector:
    run: admin-client
