apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-configmap
data:
  DBHOST: {{ if .Values.global }}{{ .Values.global.postgres.host }}{{else}}postgres{{ end }}
  POSTGRESQLHANGFIRE_DBNAME: {{ .Values.app.postgres.dbnameHangfire | quote }}
  POSTGRESQLBILLING_DBNAME: {{ .Values.app.postgres.dbnameBilling | quote }}
