apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  selector:
    matchLabels:
      run: billing
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: billing
    spec:
      containers:
        - name: billing
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: billing-configmap
                  key: DBHOST
            - name: POSTGRESQLHANGFIRE_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: billing-configmap
                  key: POSTGRESQLHANGFIRE_DBNAME
            - name: POSTGRESQLHANGFIRE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: userHangfire
            - name: POSTGRESQLHANGFIRE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: passwordHangfire
            - name: POSTGRESQLBILLING_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: billing-configmap
                  key: POSTGRESQLBILLING_DBNAME
            - name: POSTGRESQLBILLING_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: userBackend
            - name: POSTGRESQLBILLING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: passwordBackend
