apiVersion: v1
kind: Service
metadata:
  name: billing
  labels:
    run: billing
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
  selector:
    run: billing
