---
- name: Deploy service
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Terraform init
      command: terraform init
      args:
        chdir: ../terraform/

    - name: Terraform apply
      command: terraform apply -auto-approve
      args:
        chdir: ../terraform/

    - name: Get new IP
      command: terraform output external_ip_address_vm_1
      register: external_ip_address
      args:
        chdir: ../terraform/

    - name: Change inventory
      lineinfile:
        path: inventories/stage/hosts
        regexp: '#server_ip'
        line: "{{external_ip_address.stdout}} #server_ip"

    - name: Change stage for test
      lineinfile:
        path: ../tests/codeception.yml
        regexp: '#stage_ip'
        line: "              url: http://{{external_ip_address.stdout}}:7000/api/v1 #stage_ip"

    - name: Reset host
      command: "ssh-keygen -f ~/.ssh/known_hosts -R {{external_ip_address.stdout}}"

    - name: Add host
      command: "ssh-keyscan -H {{external_ip_address.stdout}} >> ~/.ssh/known_hosts"

    - debug: var=external_ip_address.stdout
