apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  DB_HOST: {{ if .Values.global }}{{ .Values.global.postgres.host }}{{else}}postgres{{ end }}
  DB_DATABASE: {{ .Values.app.postgres.db | quote }}
