apiVersion: v1
kind: Service
metadata:
  name: position
  labels:
    run: position
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    run: position
