apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-configmap
data:
  APP_PORT: {{ .Values.app.port | quote }}
  APP_CATALOG: {{ .Values.app.catalog | quote }}
  AWS_REGION: {{ .Values.app.aws.region | quote }}
