apiVersion: v1
kind: Service
metadata:
  name: backup
  labels:
    run: backup
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
  selector:
    run: backup
