apiVersion: apps/v1
kind: Deployment
metadata:
  name: rc-flyway
spec:
  selector:
    matchLabels:
      run: rc-flyway
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: rc-flyway
    spec:
      containers:
        - name: busybox
          image: busybox:1.28
          command: ['sh', '-c', 'tail -f /dev/null']
      initContainers:
        - name: flyway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/flyway/flyway"]
          args: ["migrate"]
          env:
            - name: FLYWAY_SCHEMAS
              valueFrom:
                configMapKeyRef:
                  name: rc-flyway-configmap
                  key: FLYWAY_SCHEMAS
            - name: FLYWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: rc-flyway-configmap
                  key: FLYWAY_URL
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: user
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
