apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppa
spec:
  selector:
    matchLabels:
      run: ppa
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: ppa
    spec:
      containers:
        - name: ppa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PHP_PG_ADMIN_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: ppa-configmap
                  key: PHP_PG_ADMIN_SERVER_HOST
