apiVersion: v1
kind: Service
metadata:
  name: ppa
  labels:
    run: ppa
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    run: ppa
