apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      run: web
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /api/v1/version
              port: 80
          readinessProbe:
            httpGet:
              path: /api/v1/version
              port: 80
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: web-configmap
                  key: JDBC_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: web
                  key: jwtSecret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: userBackend
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: passwordBackend
