apiVersion: v1
kind: Service
metadata:
  name: convey
  labels:
    run: convey
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    run: convey
